import pandas as pd
import numpy as np

def run_backtest(df: pd.DataFrame, initial_capital: float = 10000.0, interval: str = '1d'):
    """
    Simulates a strategy based on the signals generated by analyzer.py.
    """
    if df.empty:
        return None

    data = df.copy()

    # Re-implementing score logic in a vectorized way for backtesting
    score = pd.Series(0, index=data.index)

    # RSI check
    if 'RSI' in data.columns:
        score.loc[data['RSI'] < 30] += 1
        score.loc[data['RSI'] > 70] -= 1

    # MACD check
    macd_col = 'MACD_12_26_9'
    signal_col = 'MACDs_12_26_9'
    if macd_col in data.columns and signal_col in data.columns:
        score.loc[data[macd_col] > data[signal_col]] += 1
        score.loc[data[macd_col] <= data[signal_col]] -= 1

    # EMA Trend check
    if 'EMA_50' in data.columns:
        score.loc[data['Close'] > data['EMA_50']] += 1
        score.loc[data['Close'] <= data['EMA_50']] -= 1

    # Divergence
    if 'Bullish_Divergence' in data.columns:
        score.loc[data['Bullish_Divergence']] += 2
    if 'Bearish_Divergence' in data.columns:
        score.loc[data['Bearish_Divergence']] -= 2

    data['Signal'] = 0
    data.loc[score >= 2, 'Signal'] = 1
    data.loc[score <= -2, 'Signal'] = -1

    # Assume we stay in the position until the opposite signal
    data['Position'] = data['Signal'].replace(0, np.nan).ffill().fillna(0)

    # Calculate daily returns
    data['Market_Return'] = data['Close'].pct_change()
    data['Strategy_Return'] = data['Market_Return'] * data['Position'].shift(1)

    # Cumulative returns
    data['Cum_Market_Return'] = (1 + data['Market_Return']).cumprod()
    data['Cum_Strategy_Return'] = (1 + data['Strategy_Return']).cumprod()

    # Metrics
    total_return = data['Cum_Strategy_Return'].iloc[-1] - 1
    buy_hold_return = data['Cum_Market_Return'].iloc[-1] - 1

    # Drawdown
    rolling_max = data['Cum_Strategy_Return'].cummax()
    drawdown = (data['Cum_Strategy_Return'] - rolling_max) / rolling_max
    max_drawdown = drawdown.min()

    # Sharpe Ratio Annualization Factor
    # Default to 252 (daily)
    ann_factor = 252
    if 'h' in interval:
        ann_factor = 252 * 24
    elif 'm' in interval:
        ann_factor = 252 * 24 * 60
    elif 't' in interval or 's' in interval:
        ann_factor = 252 * 24 * 3600 # rough estimate for high frequency

    sharpe_ratio = (data['Strategy_Return'].mean() / data['Strategy_Return'].std()) * np.sqrt(ann_factor) if data['Strategy_Return'].std() != 0 else 0

    results = {
        'Total Return': f"{total_return:.2%}",
        'Buy & Hold Return': f"{buy_hold_return:.2%}",
        'Max Drawdown': f"{max_drawdown:.2%}",
        'Sharpe Ratio': f"{sharpe_ratio:.2f}",
        'Final Capital': f"{initial_capital * (1 + total_return):.2f}"
    }

    return results, data
